name=PIDReg
version=1.0.0
author=Savelii Yam <https://github.com/SaveliiYam>
maintainer=Savelii Yam <https://github.com/SaveliiYam>
sentence=PID regulator with interface and anti-windup.
paragraph=Provides IPidController interface and PidController class for embedded control loops on Arduino and PlatformIO.
category=Signal Input/Output
url=https://github.com/SaveliiYam/PID-Regulator
architectures=*
includes=PidController.h
license=MIT
